language: node_js
node_js:
- "0.10"
env:
  global:
  - secure: Ua2I2Cg5vo8bJagk8vstG2G+yo0g8oXzcxS1xk83lwAXgqxGcsJ/yrisncGk6XurRUqqVu+iBsRr1U+DMM11Giir0yLReZK73/VzcM3pt5dE0UkFCswiy0vp8Tp+402yor0Rk2NUMg8NyZRAEgTH1o/ORAYQMIT+KUjXy68/G78=
  - secure: OYgSKe1VkhhYkm04o3YLS5nuvK7OJwUcSdm97nt4qJCCU0ehC/9jtJR3gzePP90jmr16bvi6rDumaJdS/ttVr6RaF3y3NcACYLY/fDD7oWRZfaInCmL3pYW+/wJwI8caMDOVVmAEuM6NIdIt3pNaoGzm5bFzOuqiNol/D9RRNAc=
