// Generated by CoffeeScript 1.7.1
var createIframe, injectFunc;

createIframe = function() {
  var iframe, style;
  iframe = document.createElement('IFRAME');
  style = iframe.style;
  style.width = style.height = '1px';
  style.left = style.top = '-10px';
  style.position = 'absolute';
  return document.body.appendChild(iframe);
};

injectFunc = function(iframe, fn, opts) {
  var contentWindow, iframeDoc, script;
  contentWindow = iframe.contentWindow;
  iframeDoc = contentWindow.document;
  script = iframeDoc.createElement('SCRIPT');
  script.innerHTML = "var fn = " + (fn.toString()) + ";";
  iframeDoc.body.appendChild(script);
  return contentWindow.fn(opts);
};

module.exports = function(fn, opts, callback) {
  var iframe;
  iframe = createIframe();
  return setTimeout(function() {
    return callback(null, injectFunc(iframe, fn, opts));
  });
};
